#!/bin/sh

# Find the top of the workspace regardless of where this script was
# started from
SCRIPT_DIR=`dirname $0`
START_DIR=`pwd`
REL_PATH_TO_WS=".."
WS_DIR=`cd ${START_DIR}/${SCRIPT_DIR}/${REL_PATH_TO_WS} && pwd`

$WS_DIR/anvil/src/main/python/anvil $*
